# The Sequence of Neutrosophic Soft Sets

In [5]:
from nssseq import *
about()

Python Package for Sequence of Neutrosophic Soft Sets
Authors: Quang-Thinh Bui, My-Phuong Ngo, and Bay Vo
Version: Command Line v.1.0
Paper: The Sequence of Neutrosophic Soft Sets and Its
       Decision-Making Problem in Medical Diagnosis


## 1. Neutrosophic Soft Sets

In [6]:
from nssseq import *
m,a = readfromfile("nss_A.txt")
m,b = readfromfile("nss_B.txt")
print(complement(m,a))
print("-----")
print(intersection(m,a,b))
print("-----")
print(union(m,a,b))

[[[[0.2 0.4 0.1]
   [0.2 0.9 0.3]
   [0.5 0.4 0.3]
   [0.7 0.3 0.1]]

  [[0.4 0.7 0.4]
   [0.9 0.7 0.5]
   [0.1 0.8 0.4]
   [0.1 0.6 0.2]]

  [[0.5 0.3 0.2]
   [0.4 0.5 0.2]
   [0.4 0.4 0.7]
   [0.7 0.2 0.9]]

  [[0.9 0.9 0.8]
   [0.2 0.6 0.4]
   [0.3 0.8 0.1]
   [0.2 0.5 0.3]]

  [[0.2 0.4 0.3]
   [0.1 0.9 0.1]
   [0.7 0.4 0.5]
   [0.4 0.8 0.2]]]]
-----
[[[[0.1 0.5 0.2]
   [0.1 0.1 0.3]
   [0.2 0.6 0.6]
   [0.1 0.7 0.7]]

  [[0.1 0.3 0.4]
   [0.2 0.3 0.9]
   [0.2 0.2 0.3]
   [0.1 0.4 0.4]]

  [[0.2 0.5 0.5]
   [0.2 0.1 0.5]
   [0.7 0.6 0.9]
   [0.2 0.2 0.7]]

  [[0.4 0.1 0.9]
   [0.1 0.2 0.3]
   [0.1 0.2 0.6]
   [0.3 0.4 0.4]]

  [[0.3 0.6 0.3]
   [0.1 0.1 0.2]
   [0.1 0.4 0.7]
   [0.1 0.2 0.7]]]]
-----
[[[[0.2 0.6 0.1]
   [0.3 0.2 0.2]
   [0.3 0.8 0.5]
   [0.3 0.7 0.4]]

  [[0.4 0.3 0.4]
   [0.5 0.4 0.3]
   [0.4 0.3 0.1]
   [0.2 0.5 0.1]]

  [[0.3 0.7 0.4]
   [0.2 0.5 0.4]
   [0.7 0.8 0.4]
   [0.9 0.8 0.3]]

  [[0.8 0.6 0.3]
   [0.4 0.4 0.2]
   [0.2 0.5 0.3]
   [0.4 0.5 0.2]]

  [[0.

## 2. The Subsequence of Neutrosophic Soft Sets

In [13]:
from nssseq import *
n,f = readfromfile("subseq_A.txt")
n,g = readfromfile("subseq_B.txt")
print(issubnssseq(n,f,g))

1


## 3. Operations on Sequences of Neutrosophic Soft Sets

In [14]:
from nssseq import *
k,z = readfromfile("seq_comp.txt")
print(complement(k,z))

[[[[0.5 0.8 0.1]
   [0.9 0.9 0.4]
   [0.6 0.2 0.2]
   [0.6 0.9 0.9]]

  [[0.6 0.3 0.3]
   [0.5 0.7 0.4]
   [0.3 0.7 0.2]
   [0.3 0.5 0.4]]

  [[0.5 0.6 0.8]
   [0.7 0.5 0.2]
   [0.9 0.2 0.7]
   [0.8 0.5 0.3]]]


 [[[0.9 0.3 0.1]
   [0.9 0.4 0.3]
   [0.6 0.5 0.2]
   [0.9 0.5 0.4]]

  [[0.4 0.8 0.2]
   [0.2 0.6 0.8]
   [0.8 0.4 0.5]
   [0.4 0.9 0.1]]

  [[0.3 0.9 0.5]
   [0.4 0.7 0.1]
   [0.7 0.5 0.3]
   [0.7 0.5 0.5]]]


 [[[0.7 0.2 0.1]
   [0.7 0.5 0.3]
   [0.5 0.4 0.7]
   [0.9 0.8 0.7]]

  [[0.4 0.5 0.6]
   [0.9 0.1 0.7]
   [0.5 0.9 0.1]
   [0.3 0.8 0.5]]

  [[0.2 0.7 0.3]
   [0.6 0.5 0.3]
   [0.9 0.2 0.8]
   [0.6 0.5 0.1]]]]


In [16]:
k,x = readfromfile("seq_A.txt")
k,y = readfromfile("seq_B.txt")
print(intersection(k,x,y))
print("-----")
print(union(k,x,y))
print("-----")
print(difference(k,x,y))

[[[[0.1 0.2 0.4]
   [0.1 0.2 0.5]
   [0.2 0.5 0.6]
   [0.2 0.8 0.9]]

  [[0.2 0.1 0.4]
   [0.1 0.1 0.9]
   [0.2 0.3 0.8]
   [0.2 0.3 0.9]]

  [[0.6 0.7 0.9]
   [0.2 0.5 0.7]
   [0.3 0.7 0.9]
   [0.5 0.1 0.9]]]


 [[[0.4 0.4 0.7]
   [0.3 0.3 0.5]
   [0.2 0.1 0.6]
   [0.2 0.3 0.6]]

  [[0.2 0.3 0.3]
   [0.1 0.1 0.7]
   [0.1 0.4 0.7]
   [0.1 0.1 0.9]]

  [[0.3 0.4 0.8]
   [0.2 0.2 0.6]
   [0.2 0.2 0.7]
   [0.3 0.5 0.8]]]


 [[[0.1 0.1 0.7]
   [0.1 0.3 0.9]
   [0.8 0.4 0.7]
   [0.3 0.2 0.5]]

  [[0.3 0.1 0.3]
   [0.3 0.3 0.5]
   [0.5 0.1 0.9]
   [0.5 0.7 0.4]]

  [[0.1 0.3 0.4]
   [0.1 0.3 0.8]
   [0.2 0.3 0.9]
   [0.3 0.5 0.5]]]]
-----
[[[[0.3 0.5 0.3]
   [0.1 0.6 0.3]
   [0.2 0.8 0.6]
   [0.7 0.9 0.6]]

  [[0.6 0.5 0.4]
   [0.6 0.8 0.9]
   [0.7 0.5 0.3]
   [0.7 0.6 0.3]]

  [[0.7 0.8 0.9]
   [0.3 0.6 0.4]
   [0.7 0.8 0.5]
   [0.7 0.8 0.9]]]


 [[[0.8 0.5 0.2]
   [0.3 0.8 0.2]
   [0.3 0.5 0.6]
   [0.7 0.5 0.1]]

  [[0.9 0.6 0.2]
   [0.6 0.3 0.3]
   [0.4 0.7 0.7]
   [0.8 0.4 0.7]]

  [[0.5

## 4. Distance Measures on Sequences of Neutrosophic Soft Sets

In [17]:
from nssseq import *
k,x = readfromfile("seq_A.txt")
k,y = readfromfile("seq_B.txt")
print(manhattan_distance(k,x,y))
print("-----")
print(euclid_distance(k,x,y))
print("-----")
print(lpnorm_distance(k,5,x,y))
print("-----")
print(chebyshev_distance(k,x,y))
print("-----")
print(manhattan_dist(k,x,y))
print("-----")
print(euclid_dist(k,x,y))
print("-----")
print(lpnorm_dist(k,5,x,y))
print("-----")
print(chebyshev_dist(k,x,y))

10.033333333333331
-----
3.5862546786641136
-----
1.5751259815763579
-----
2.2
-----
0.2787037037037037
-----
0.3450875173515468
-----
0.31941682706019686
-----
0.7333333333333334


## 5. The Application of Sequence of Neutrosophic Soft Sets

## A.	The Maji's Algorithm: From Set to Sequence

In [6]:
import numpy as np
from maji_nss import *
######
at1 = [[0.6, 0.3, 0.1],[0.2, 0.3, 0.4],[0.9, 0.6, 0.7]]
bt1 = [[0.1, 0.4, 0.6],[0.8, 0.3, 0.6],[0.2, 0.6, 0.9]]
ct1 = [[0.4, 0.6, 0.2],[0.3, 0.5, 0.2],[0.6, 0.9, 0.6]]
dt1 = [[0.3, 0.3, 0.4],[0.1, 0.7, 0.6],[0.2, 0.6, 0.4]]
######
mat = np.array([at1,bt1,ct1,dt1])
######
s = [4,3]
######
print("The Maji’s Algorithm for NS-Set in Decision-Making Problem")
print("")
print("> Step 1. Comparison Matrix")
print(matrix(s,mat))
print("")
print("> Step 2. Object Scores")
print(score(s,mat))
print("")
print("> Step 3. Output")
print(maji(s,mat))

The Maji’s Algorithm for NS-Set in Decision-Making Problem

> Step 1. Comparison Matrix
[[ 4  1  3]
 [-1  1  0]
 [ 4  4  4]
 [ 0  0  3]]

> Step 2. Object Scores
[ 8  0 12  3]

> Step 3. Output
3


In [3]:
from nssseq import *
at1 = [[0.6, 0.4, 0.2],[0.3, 0.2, 0.2],[0.3, 0.1, 0.4]]
bt1 = [[0.2, 0.1, 0.2],[0.1, 0.1, 0.7],[0.2, 0.2, 0.3]]
ct1 = [[0.1, 0.2, 0.3],[0.1, 0.4, 0.3],[0.7, 0.3, 0.4]]
dt1 = [[0.7, 0.5, 0.6],[0.5, 0.7, 0.1],[0.8, 0.4, 0.5]]
A = np.array([at1,bt1,ct1,dt1])
##
at2 = [[0.3, 0.4, 0.2],[0.1, 0.4, 0.1],[0.2, 0.1, 0.6]]
bt2 = [[0.1, 0.2, 0.4],[0.7, 0.2, 0.3],[0.4, 0.7, 0.7]]
ct2 = [[0.2, 0.6, 0.7],[0.8, 0.4, 0.5],[0.6, 0.5, 0.8]]
dt2 = [[0.3, 0.5, 0.4],[0.9, 0.8, 0.7],[0.7, 0.3, 0.9]]
B = np.array([at2,bt2,ct2,dt2])
######
mat = np.array([A,B])
######
s = [2,4,3]
w = [1,1]
print("")
print("The Maji’s Algorithm for NSS-Sequence in Decision-Making Problem")
print("")
print("> Step 1. Presentation Matrix")
print(transform(s,mat,normal(w)))
print("")
print("> Step 2. Comparison Matrix")
print(matrix(s,transform(s,mat,normal(w))))
print("")
print("> Step 3. Object Scores")
print(score(s,transform(s,mat,normal(w))))
print("")
print("> Step 4. Output: ")
print(maji(s,transform(s,mat,normal(w))))


The Maji’s Algorithm for NSS-Sequence in Decision-Making Problem

> Step 1. Presentation Matrix
[[[0.45 0.4  0.2 ]
  [0.2  0.3  0.15]
  [0.25 0.1  0.5 ]]

 [[0.15 0.15 0.3 ]
  [0.4  0.15 0.5 ]
  [0.3  0.45 0.5 ]]

 [[0.15 0.4  0.5 ]
  [0.45 0.4  0.4 ]
  [0.65 0.4  0.6 ]]

 [[0.5  0.5  0.5 ]
  [0.7  0.75 0.4 ]
  [0.75 0.35 0.7 ]]]

> Step 2. Comparison Matrix
[[ 4  1 -1]
 [ 0 -2  3]
 [ 0  2  2]
 [ 3  4  1]]

> Step 3. Object Scores
[4 1 4 8]

> Step 4. Output: 
4


## B. The Application of Sequence of Neutrosophic Soft Sets

In [1]:
from nssseq import *
s, mat = readfromfile("nssseq_application.txt")
w = [1,1,1,1]
print("")
print("The Maji’s Algorithm for NSS-Sequence in Decision-Making Problem")
print("")
print("> Step 1. Presentation Matrix")
print(transform(s,mat,normal(w)))
print("")
print("> Step 2. Comparison Matrix")
print(matrix(s,transform(s,mat,normal(w))))
print("")
print("> Step 3. Object Scores")
print(score(s,transform(s,mat,normal(w))))
print("")
print("> Step 4. Output: ")
print(maji(s,transform(s,mat,normal(w))))


The Maji’s Algorithm for NSS-Sequence in Decision-Making Problem

> Step 1. Presentation Matrix
[[[0.3  0.25 0.38]
  [0.48 0.38 0.38]
  [0.5  0.22 0.15]
  [0.22 0.22 0.38]]

 [[0.4  0.43 0.45]
  [0.55 0.28 0.35]
  [0.4  0.32 0.5 ]
  [0.2  0.45 0.4 ]]

 [[0.22 0.5  0.52]
  [0.55 0.3  0.42]
  [0.32 0.38 0.52]
  [0.35 0.35 0.42]]

 [[0.32 0.35 0.68]
  [0.5  0.33 0.38]
  [0.42 0.45 0.38]
  [0.48 0.18 0.62]]

 [[0.5  0.4  0.57]
  [0.55 0.5  0.32]
  [0.43 0.4  0.4 ]
  [0.45 0.38 0.52]]]

> Step 2. Comparison Matrix
[[ 1  0  4  2]
 [ 5  3 -1  3]
 [ 2  1 -2  2]
 [-1  0  5  0]
 [ 3  8  4  3]]

> Step 3. Object Scores
[ 7 10  3  4 18]

> Step 4. Output: 
5


## C. Comparative study of decision making algorithms between NSS-sequence and tNS-set

In [5]:
import numpy as np
from maji_tnss import *
######
at1 = [[0.5,0.2,0.4],[0.7,0.1,0.2],[0.8,0.2,0.1],[0.4,0.4,0.4],[0.9,0.1,0.1]]
bt1 = [[0.3,0.1,0.5],[0.6,0.4,0.2],[0.6,0.4,0.1],[0.1,0.3,0.4],[0.4,0.4,0.1]]
ct1 = [[0.4,0.2,0.3],[0.2,0.2,0.6],[0.3,0.3,0.5],[0.5,0.6,0.4],[0.6,0.3,0.2]]
dt1 = [[0.4,0.2,0.3],[0.4,0.2,0.3],[0.4,0.2,0.3],[0.5,0.3,0.4],[0.3,0.2,0.7]]
A = np.array([at1,bt1,ct1,dt1])
##
at2 = [[0.7,0.2,0.3],[0.6,0.1,0.4],[0.5,0.3,0.6],[0.4,0.2,0.7],[0.2,0.4,0.6]]
bt2 = [[0.5,0.1,0.2],[0.5,0.3,0.5],[0.3,0.4,0.6],[0.5,0.4,0.3],[0.7,0.4,0.2]]
ct2 = [[0.5,0.3,0.4],[0.3,0.3,0.4],[0.1,0.3,0.5],[0.4,0.3,0.3],[0.4,0.3,0.5]]
dt2 = [[0.5,0.3,0.4],[0.7,0.3,0.1],[0.4,0.2,0.3],[0.7,0.2,0.1],[0.3,0.3,0.5]]
B = np.array([at2,bt2,ct2,dt2])
##
at3 = [[0.7,0.1,0.1],[0.1,0.5,0.5],[0.9,0.4,0.1],[0.3,0.5,0.4],[0.1,0.6,0.6]]
bt3 = [[0.8,0.2,0.1],[0.5,0.3,0.2],[0.7,0.3,0.1],[0.6,0.3,0.1],[0.6,0.2,0.3]]
ct3 = [[0.7,0.1,0.3],[0.4,0.2,0.3],[0.5,0.5,0.1],[0.5,0.2,0.2],[0.5,0.3,0.4]]
dt3 = [[0.4,0.2,0.3],[0.4,0.2,0.3],[0.4,0.2,0.3],[0.5,0.3,0.3],[0.5,0.3,0.4]]
C = np.array([at3,bt3,ct3,dt3])
######
mat = np.array([A,B,C])
######
s = [3,4,5]
w = [0.3,0.5,0.8]
######
print("The Maji’s Algorithm for tNS-set in Decision-Making Problem")
print("")
print("> Step 1. Presentation Matrix")
m = transform(s,mat,w)
print(m)
print("")
print("> Step 2. Comparison Matrix")
print(matrix(s,m))
print("")
print("> Step 3. Object Scores")
print(score(s,m))
print("")
print("> Step 4. Output")
print(maji(s,m))

The Maji’s Algorithm for tNS-set in Decision-Making Problem

> Step 1. Presentation Matrix
[[[0.44 0.1  0.15]
  [0.25 0.2  0.27]
  [0.5  0.22 0.17]
  [0.23 0.26 0.33]
  [0.19 0.3  0.34]]

 [[0.41 0.1  0.14]
  [0.35 0.21 0.2 ]
  [0.37 0.23 0.17]
  [0.32 0.22 0.15]
  [0.4  0.2  0.15]]

 [[0.39 0.12 0.22]
  [0.22 0.15 0.26]
  [0.22 0.27 0.2 ]
  [0.31 0.2  0.18]
  [0.32 0.2  0.26]]

 [[0.29 0.15 0.22]
  [0.33 0.15 0.16]
  [0.27 0.13 0.2 ]
  [0.37 0.18 0.17]
  [0.27 0.19 0.32]]]

> Step 2. Comparison Matrix
[[ 3  0  3  0  0]
 [ 3  5  3  4  5]
 [ 0 -1  0  0  3]
 [ 0  3 -2  2 -1]]

> Step 3. Object Scores
[ 6 20  2  2]

> Step 4. Output
2
