# Neutrosophic Soft Set -- Pabitra Kumar Maji

In [1]:
import numpy as np
from nss import *
######
at1 = [[0.6, 0.3, 0.8],[0.5, 0.2, 0.6],[0.7, 0.3, 0.4],[0.8, 0.5, 0.6],[0.6, 0.7, 0.2]]
bt1 = [[0.7, 0.2, 0.6],[0.6, 0.3, 0.7],[0.7, 0.5, 0.6],[0.6, 0.8, 0.3],[0.8, 0.1, 0.8]]
ct1 = [[0.8, 0.3, 0.4],[0.8, 0.5, 0.1],[0.3, 0.5, 0.6],[0.7, 0.2, 0.1],[0.7, 0.2, 0.6]]
dt1 = [[0.7, 0.5, 0.6],[0.6, 0.8, 0.7],[0.7, 0.6, 0.8],[0.8, 0.3, 0.6],[0.8, 0.3, 0.8]]
et1 = [[0.8, 0.6, 0.7],[0.5, 0.6, 0.8],[0.8, 0.7, 0.6],[0.7, 0.8, 0.3],[0.7, 0.2, 0.6]]
######
mat = np.array([at1,bt1,ct1,dt1,et1])
######
s = [5,5]
######
welcome()
print("")
print("The Maji’s Algorithm for NS-Set in Decision-Making Problem")
print("")
print("> Step 1. Comparison Matrix: ")
print(compmat(mat,s))
print("")
print("> Step 2. Object Scores: ")
print(score(mat,s))
print("")
print("> Step 3. Output: ")
print(maji(mat,s))

Python Package for Sequence of Neutrosophic Soft Sets
Authors: Quang-Thinh BUI, My-Phuong NGO, and Bay Vo
Version: Command Line v.1.0
Paper: The Sequence of Neutrosophic Soft Sets and Its
       Decision-Making Problem in Medical Diagnosis

The Maji’s Algorithm for NS-Set in Decision-Making Problem

> Step 1. Comparison Matrix: 
[[-2  0  3  2  4]
 [ 0  1  2  2  0]
 [ 6  6 -1  2  2]
 [ 3  4  2  1  3]
 [ 5  0  5  4  2]]

> Step 2. Object Scores: 
[ 7  5 15 13 16]

> Step 3. Output: 
5
