# The Sequence of Neutrosophic Soft Sets

In [1]:
from nssseq import *
about()

Python Package for Sequence of Neutrosophic Soft Sets
Authors: Quang-Thinh Bui, My-Phuong Ngo, and Bay Vo
Version: Command Line v.1.0
Paper: The Sequence of Neutrosophic Soft Sets and Its
       Decision-Making Problem in Medical Diagnosis


## 1. Neutrosophic Soft Sets

In [2]:
from nssseq import *
m,a = readfromfile("nss_A.txt")
m,b = readfromfile("nss_B.txt")
print(complement(m,a))
print("-----")
print(intersection(m,a,b))
print("-----")
print(union(m,a,b))

[[[[0.2 0.4 0.1]
   [0.2 0.9 0.3]
   [0.5 0.4 0.3]
   [0.7 0.3 0.1]]

  [[0.4 0.7 0.4]
   [0.9 0.7 0.5]
   [0.1 0.8 0.4]
   [0.1 0.6 0.2]]

  [[0.5 0.3 0.2]
   [0.4 0.5 0.2]
   [0.4 0.4 0.7]
   [0.7 0.2 0.9]]

  [[0.9 0.9 0.8]
   [0.2 0.6 0.4]
   [0.3 0.8 0.1]
   [0.2 0.5 0.3]]

  [[0.2 0.4 0.3]
   [0.1 0.9 0.1]
   [0.7 0.4 0.5]
   [0.4 0.8 0.2]]]]
-----
[[[[0.2 0.4 0.1]
   [0.1 0.2 0.3]
   [0.2 0.4 0.6]
   [0.3 0.3 0.4]]

  [[0.1 0.3 0.4]
   [0.2 0.4 0.5]
   [0.1 0.3 0.4]
   [0.1 0.5 0.4]]

  [[0.3 0.3 0.4]
   [0.2 0.1 0.5]
   [0.4 0.4 0.9]
   [0.2 0.2 0.9]]

  [[0.4 0.6 0.8]
   [0.1 0.2 0.4]
   [0.2 0.5 0.6]
   [0.2 0.4 0.4]]

  [[0.2 0.4 0.3]
   [0.1 0.2 0.2]
   [0.1 0.4 0.7]
   [0.1 0.4 0.7]]]]
-----
[[[[0.2 0.5 0.1]
   [0.1 0.2 0.3]
   [0.2 0.8 0.6]
   [0.3 0.7 0.4]]

  [[0.1 0.3 0.4]
   [0.2 0.4 0.3]
   [0.2 0.3 0.3]
   [0.1 0.5 0.4]]

  [[0.3 0.5 0.4]
   [0.2 0.1 0.5]
   [0.7 0.8 0.9]
   [0.2 0.2 0.3]]

  [[0.4 0.6 0.3]
   [0.1 0.2 0.3]
   [0.2 0.5 0.6]
   [0.4 0.4 0.4]]

  [[0.

## 2. The Subsequence of Neutrosophic Soft Sets

In [3]:
from nssseq import *
n,f = readfromfile("subnssseq_A.txt")
n,g = readfromfile("subnssseq_B.txt")
print(issubnssseq(n,f,g))

1


## 3. Operations on Sequences of Neutrosophic Soft Sets

In [4]:
from nssseq import *
k,z = readfromfile("nssseq_A.txt")
print(complement(k,z))

[[[[0.5 0.8 0.1]
   [0.9 0.9 0.4]
   [0.6 0.2 0.2]
   [0.6 0.9 0.9]]

  [[0.6 0.3 0.3]
   [0.5 0.7 0.4]
   [0.3 0.7 0.2]
   [0.3 0.5 0.4]]

  [[0.5 0.6 0.8]
   [0.7 0.5 0.2]
   [0.9 0.2 0.7]
   [0.8 0.5 0.3]]]


 [[[0.9 0.3 0.1]
   [0.9 0.4 0.3]
   [0.6 0.5 0.2]
   [0.9 0.5 0.4]]

  [[0.4 0.8 0.2]
   [0.2 0.6 0.8]
   [0.8 0.4 0.5]
   [0.4 0.9 0.1]]

  [[0.3 0.9 0.5]
   [0.4 0.7 0.1]
   [0.7 0.5 0.3]
   [0.7 0.5 0.5]]]


 [[[0.7 0.2 0.1]
   [0.7 0.5 0.3]
   [0.5 0.4 0.7]
   [0.9 0.8 0.7]]

  [[0.4 0.5 0.6]
   [0.9 0.1 0.7]
   [0.5 0.9 0.1]
   [0.3 0.8 0.5]]

  [[0.2 0.7 0.3]
   [0.6 0.5 0.3]
   [0.9 0.2 0.8]
   [0.6 0.5 0.1]]]]


In [5]:
k,x = readfromfile("nssseq_B.txt")
k,y = readfromfile("nssseq_C.txt")
print(intersection(k,x,y))
print("-----")
print(union(k,x,y))
print("-----")
print(difference(k,x,y))

[[[[0.1 0.2 0.4]
   [0.1 0.2 0.5]
   [0.2 0.5 0.6]
   [0.2 0.8 0.9]]

  [[0.2 0.1 0.4]
   [0.1 0.1 0.9]
   [0.2 0.3 0.8]
   [0.2 0.3 0.9]]

  [[0.6 0.7 0.9]
   [0.2 0.5 0.7]
   [0.3 0.7 0.9]
   [0.5 0.1 0.9]]]


 [[[0.4 0.4 0.7]
   [0.3 0.3 0.5]
   [0.2 0.1 0.6]
   [0.2 0.3 0.6]]

  [[0.2 0.3 0.3]
   [0.1 0.1 0.7]
   [0.1 0.4 0.7]
   [0.1 0.1 0.9]]

  [[0.3 0.4 0.8]
   [0.2 0.2 0.6]
   [0.2 0.2 0.7]
   [0.3 0.5 0.8]]]


 [[[0.1 0.1 0.7]
   [0.1 0.3 0.9]
   [0.8 0.4 0.7]
   [0.3 0.2 0.5]]

  [[0.3 0.1 0.3]
   [0.3 0.3 0.5]
   [0.5 0.1 0.9]
   [0.5 0.7 0.4]]

  [[0.1 0.3 0.4]
   [0.1 0.3 0.8]
   [0.2 0.3 0.9]
   [0.3 0.5 0.5]]]]
-----
[[[[0.1 0.2 0.3]
   [0.1 0.6 0.5]
   [0.2 0.5 0.6]
   [0.7 0.9 0.9]]

  [[0.6 0.5 0.4]
   [0.1 0.1 0.9]
   [0.7 0.5 0.8]
   [0.7 0.6 0.9]]

  [[0.7 0.8 0.9]
   [0.3 0.6 0.7]
   [0.3 0.7 0.5]
   [0.5 0.1 0.9]]]


 [[[0.4 0.5 0.7]
   [0.3 0.3 0.2]
   [0.3 0.1 0.6]
   [0.7 0.3 0.1]]

  [[0.2 0.3 0.2]
   [0.6 0.3 0.7]
   [0.4 0.7 0.7]
   [0.8 0.1 0.9]]

  [[0.3

## 4. Distance Measures on Sequences of Neutrosophic Soft Sets

In [6]:
from nssseq import *
k,x = readfromfile("nssseq_B.txt")
k,y = readfromfile("nssseq_C.txt")
print(manhattan_distance(k,x,y))
print("-----")
print(euclid_distance(k,x,y))
print("-----")
print(lpnorm_distance(k,5,x,y))
print("-----")
print(chebyshev_distance(k,x,y))
print("-----")
print(manhattan_dist(k,x,y))
print("-----")
print(euclid_dist(k,x,y))
print("-----")
print(lpnorm_dist(k,5,x,y))
print("-----")
print(chebyshev_dist(k,x,y))

10.033333333333331
-----
3.5862546786641136
-----
1.5751259815763579
-----
2.2
-----
0.2787037037037037
-----
0.3450875173515468
-----
0.31941682706019686
-----
0.7333333333333334


## 5. The Application of Subsequence of Neutrosophic Soft Sets

### 5.1. The First Scenario

In [7]:
s, mat = readfromfile("nssseq_application.txt")
print("")
print("The first scenario when using NSS-Sequence for decision-making problem")
print("")
print("> Step 1. Presentation Matrix")
print(transform(s,mat))
print("")
print("> Step 2. Comparison Matrix")
print(matrix(s,transform(s,mat)))
print("")
print("> Step 3. Object Scores")
print(score(s,transform(s,mat)))
print("")
print("> Step 4. Output: ")
print(maji(s,transform(s,mat)))


The first scenario when using NSS-Sequence for decision-making problem

> Step 1. Presentation Matrix
[[[0.3  0.25 0.38]
  [0.48 0.38 0.38]
  [0.5  0.22 0.15]
  [0.22 0.22 0.38]]

 [[0.4  0.43 0.45]
  [0.55 0.28 0.35]
  [0.4  0.32 0.5 ]
  [0.2  0.45 0.4 ]]

 [[0.22 0.5  0.52]
  [0.55 0.3  0.42]
  [0.32 0.38 0.52]
  [0.35 0.35 0.42]]

 [[0.32 0.35 0.68]
  [0.5  0.33 0.38]
  [0.42 0.45 0.38]
  [0.48 0.18 0.62]]

 [[0.5  0.4  0.57]
  [0.55 0.5  0.32]
  [0.43 0.4  0.4 ]
  [0.45 0.38 0.52]]]

> Step 2. Comparison Matrix
[[ 1  0  4  2]
 [ 5  3 -1  3]
 [ 2  1 -2  2]
 [-1  0  5  0]
 [ 3  8  4  3]]

> Step 3. Object Scores
[ 7 10  3  4 18]

> Step 4. Output: 
5


### 5.2. The Second Scenario

In [ ]:
s, mat = readfromfile("nssseq_application.txt")
print("")
print("The second scenario when using NSS-Sequence for decision-making problem")
print("")
print("> Step 1 & 2. Comparison Matrices and Component Object Scores")
tp = []
for i in range(s[0]):
    print(">> Matrix {}".format(i+1))
    print(matrix(s,mat[i]))
    print(">> Scores {}".format(i+1))
    print(score(s,mat[i]))
    print("")
    tp.append(score(s,mat[i]))
print("> Step 3. Object Scores")
print(sum(tp)/s[0])
print("")
print("> Step 4. Output")
print(np.argmax(sum(tp)/s[0])+1)