# Sequence of Neutrosophic Soft Sets

## The First Scenario

In [1]:
import numpy as np
from nssseq import *
######
s = [4,5,4]
mat = file("nss.sequence.txt",s)
######
welcome()
print("")
print("The first scenario when using NSS-Sequence for decision-making problem")
print("")
print("> Step 1. Presentation Matrix")
print(transform(mat,s))
print("")
print("> Step 2. Comparison Matrix")
print(compmat(transform(mat,s),s))
print("")
print("> Step 3. Object Scores")
print(score(transform(mat,s),s))
print("")
print("> Step 4. Output: ")
print(maji(transform(mat,s),s))

Python Package for Sequence of Neutrosophic Soft Sets
Authors: Quang-Thinh BUI, My-Phuong NGO, and Bay Vo
Version: Command Line v.1.0
Paper: The Sequence of Neutrosophic Soft Sets and Its
       Decision-Making Problem in Medical Diagnosis

The first scenario when using NSS-Sequence for decision-making problem

> Step 1. Presentation Matrix
[[[0.3  0.25 0.38]
  [0.48 0.38 0.38]
  [0.5  0.22 0.15]
  [0.22 0.22 0.38]]

 [[0.4  0.43 0.45]
  [0.55 0.28 0.35]
  [0.4  0.32 0.5 ]
  [0.2  0.45 0.4 ]]

 [[0.22 0.5  0.52]
  [0.55 0.3  0.42]
  [0.32 0.38 0.52]
  [0.35 0.35 0.42]]

 [[0.32 0.35 0.68]
  [0.5  0.33 0.38]
  [0.42 0.45 0.38]
  [0.48 0.18 0.62]]

 [[0.5  0.4  0.57]
  [0.55 0.5  0.32]
  [0.43 0.4  0.4 ]
  [0.45 0.38 0.52]]]

> Step 2. Comparison Matrix
[[ 1  0  4  2]
 [ 5  3 -1  3]
 [ 2  1 -2  2]
 [-1  0  5  0]
 [ 3  8  4  3]]

> Step 3. Object Scores
[ 7 10  3  4 18]

> Step 4. Output: 
5


## The Second Scenario

In [2]:
import numpy as np
from nssseq import *
######
s = [4,5,4]
mat = file("nss.sequence.txt",s)
######
welcome()
print("")
print("The second scenario when using NSS-Sequence for decision-making problem")
print("")
print("> Step 1 & 2. Comparison Matrices and Component Object Scores")
tp = []
for i in range(s[0]):
    print(">> Matrix {}".format(i+1))
    print(compmat(mat[i],s))
    print(">> Scores {}".format(i+1))
    print(score(mat[i],s))
    print("")
    tp.append(score(mat[i],s))
print("> Step 3. Object Scores")
print(sum(tp)/s[0])
print("")
print("> Step 4. Output")
print(np.argmax(sum(tp)/s[0])+1)

Python Package for Sequence of Neutrosophic Soft Sets
Authors: Quang-Thinh BUI, My-Phuong NGO, and Bay Vo
Version: Command Line v.1.0
Paper: The Sequence of Neutrosophic Soft Sets and Its
       Decision-Making Problem in Medical Diagnosis

The second scenario when using NSS-Sequence for decision-making problem

> Step 1 & 2. Comparison Matrices and Component Object Scores
>> Matrix 1
[[ 2  1  3  0]
 [-1  4 -3  7]
 [-1  3  2  1]
 [ 4  0  5  0]
 [ 7  5  6  4]]
>> Scores 1
[ 6  7  5  9 22]

>> Matrix 2
[[5 4 7 3]
 [3 3 3 2]
 [2 1 0 0]
 [1 8 5 3]
 [1 3 1 1]]
>> Scores 2
[19 11  3 17  6]

>> Matrix 3
[[-1  6  4  1]
 [ 4  2 -1  4]
 [ 8  5  4  8]
 [ 1  0  3  2]
 [ 0 -1  1 -2]]
>> Scores 3
[10  9 25  6 -2]

>> Matrix 4
[[ 1  3  2  2]
 [ 6  0  4  3]
 [-1  1 -1  0]
 [ 0  3  1  2]
 [ 3  6  3  8]]
>> Scores 4
[ 8 13 -1  6 20]

> Step 3. Object Scores
[10.75 10.    8.    9.5  11.5 ]

> Step 4. Output
5
