# Time Neutrosophic Soft Set -- Shawkat Alkhazaleh

In [2]:
import numpy as np
from tnss import *
######
at1 = [[0.5,0.2,0.4],[0.7,0.1,0.2],[0.8,0.2,0.1],[0.4,0.4,0.4],[0.9,0.1,0.1]]
bt1 = [[0.3,0.1,0.5],[0.6,0.4,0.2],[0.6,0.4,0.1],[0.1,0.3,0.4],[0.4,0.4,0.1]]
ct1 = [[0.4,0.2,0.3],[0.2,0.2,0.6],[0.3,0.3,0.5],[0.5,0.6,0.4],[0.6,0.3,0.2]]
dt1 = [[0.4,0.2,0.3],[0.4,0.2,0.3],[0.4,0.2,0.3],[0.5,0.3,0.4],[0.3,0.2,0.7]]
A = np.array([at1,bt1,ct1,dt1])
##
at2 = [[0.7,0.2,0.3],[0.6,0.1,0.4],[0.5,0.3,0.6],[0.4,0.2,0.7],[0.2,0.4,0.6]]
bt2 = [[0.5,0.1,0.2],[0.5,0.3,0.5],[0.3,0.4,0.6],[0.5,0.4,0.3],[0.7,0.4,0.2]]
ct2 = [[0.5,0.3,0.4],[0.3,0.3,0.4],[0.1,0.3,0.5],[0.4,0.3,0.3],[0.4,0.3,0.5]]
dt2 = [[0.5,0.3,0.4],[0.7,0.3,0.1],[0.4,0.2,0.3],[0.7,0.2,0.1],[0.3,0.3,0.5]]
B = np.array([at2,bt2,ct2,dt2])
##
at3 = [[0.7,0.1,0.1],[0.1,0.5,0.5],[0.9,0.4,0.1],[0.3,0.5,0.4],[0.1,0.6,0.6]]
bt3 = [[0.8,0.2,0.1],[0.5,0.3,0.2],[0.7,0.3,0.1],[0.6,0.3,0.1],[0.6,0.2,0.3]]
ct3 = [[0.7,0.1,0.3],[0.4,0.2,0.3],[0.5,0.5,0.1],[0.5,0.2,0.2],[0.5,0.3,0.4]]
dt3 = [[0.4,0.2,0.3],[0.4,0.2,0.3],[0.4,0.2,0.3],[0.5,0.3,0.3],[0.5,0.3,0.4]]
C = np.array([at3,bt3,ct3,dt3])
######
matrix = np.array([A,B,C])
######
w = [0.3,0.5,0.8]
s = [3,4,5]
######
welcome()
print("")
print("The Maji’s Algorithm for t-NSS in Decision-Making Problem")
print("")
print("> Step 1. Presentation Matrix: ")
m = transform(matrix,s,w)
print(m)
print("")
print("> Step 2. Comparison Matrix: ")
mat = compmat(m,s)
print(mat)
print("")
print("> Step 3. Object Scores: ")
print(score(m,s))
print("")
print("> Step 4. Output: ")
print(maji(m,s))

Python Package for Sequence of Neutrosophic Soft Sets
Authors: Quang-Thinh BUI, My-Phuong NGO, and Bay Vo
Version: Command Line v.1.0
Paper: The Sequence of Neutrosophic Soft Sets and Its
       Decision-Making Problem in Medical Diagnosis

The Maji’s Algorithm for t-NSS in Decision-Making Problem

> Step 1. Presentation Matrix: 
[[[0.44 0.1  0.15]
  [0.25 0.2  0.27]
  [0.5  0.22 0.17]
  [0.23 0.26 0.33]
  [0.19 0.3  0.34]]

 [[0.41 0.1  0.14]
  [0.35 0.21 0.2 ]
  [0.37 0.23 0.17]
  [0.32 0.22 0.15]
  [0.4  0.2  0.15]]

 [[0.39 0.12 0.22]
  [0.22 0.15 0.26]
  [0.22 0.27 0.2 ]
  [0.31 0.2  0.18]
  [0.32 0.2  0.26]]

 [[0.29 0.15 0.22]
  [0.33 0.15 0.16]
  [0.27 0.13 0.2 ]
  [0.37 0.18 0.17]
  [0.27 0.19 0.32]]]

> Step 2. Comparison Matrix: 
[[ 3  0  3  0  0]
 [ 3  5  3  4  5]
 [ 0 -1  0  0  3]
 [ 0  3 -2  2 -1]]

> Step 3. Object Scores: 
[ 6 20  2  2]

> Step 4. Output: 
2
